vich_uploader:
    db_driver: orm

    mappings:
       car_images:
            uri_prefix: /uploads/images/cars
            upload_destination: '%kernel.project_dir%/public//uploads/images/cars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

